name: babyaura
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Asegúrate de que la versión de Dart sea compatible

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.0.0 # Usa una versión anterior de lottie
  awesome_dialog: ^3.2.1
  provider : ^6.0.2
  
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/animacion/ # Asegúrate de que la ruta sea correcta y tengas las animaciones allí

# Si planeas usar fuentes personalizadas, descomenta y agrega las fuentes
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
